package com.smarthrms.service;
import com.smarthrms.dto.EmployeeDtos.*; import com.smarthrms.entity.*; import com.smarthrms.exception.ApiException; import com.smarthrms.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor @org.springframework.transaction.annotation.Transactional(readOnly=true) public class EmployeeService {
 private final EmployeeRepository repo; private final DepartmentRepository departments;
 private Employee find(Long id){return repo.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Employee not found"));}
 private Response out(Employee e){return new Response(e.getId(),e.getFirstName(),e.getLastName(),e.getEmail(),e.getPhone(),e.getSalary(),e.getDateOfBirth(),e.getJoiningDate(),e.getAddress(),e.getEducation(),e.getProfession(),e.getStatus(),e.getDepartment().getId(),e.getDepartment().getName());}
 public Page<Response> list(String q,Long departmentId,EmployeeStatus status,int page,int size,String sort,String dir){Sort s=Sort.by(Sort.Direction.fromString(dir),sort);Pageable p=PageRequest.of(page,Math.min(size,100),s);Page<Employee> result; if(q!=null&&!q.isBlank()) result=repo.findByFirstNameContainingIgnoreCaseOrLastNameContainingIgnoreCaseOrEmailContainingIgnoreCase(q,q,q,p); else if(departmentId!=null) result=repo.findByDepartmentId(departmentId,p); else if(status!=null) result=repo.findByStatus(status,p); else result=repo.findAll(p); return result.map(this::out);}
 @Transactional public Response create(Request r){if(repo.existsByEmail(r.email()))throw new ApiException(HttpStatus.CONFLICT,"Email already exists"); Employee e=new Employee();apply(e,r);return out(repo.save(e));}
 @Transactional public Response update(Long id,Request r){Employee e=find(id);if(repo.existsByEmailAndIdNot(r.email(),id))throw new ApiException(HttpStatus.CONFLICT,"Email already exists");apply(e,r);return out(repo.save(e));}
 private void apply(Employee e,Request r){Department d=departments.findById(r.departmentId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Department not found")); e.setFirstName(r.firstName());e.setLastName(r.lastName());e.setEmail(r.email());e.setPhone(r.phone());e.setSalary(r.salary());e.setDateOfBirth(r.dateOfBirth());e.setJoiningDate(r.joiningDate());e.setAddress(r.address());e.setEducation(r.education());e.setProfession(r.profession());e.setStatus(r.status());e.setDepartment(d);}
 public Response get(Long id){return out(find(id));}
 @Transactional public void delete(Long id){if(!repo.existsById(id))throw new ApiException(HttpStatus.NOT_FOUND,"Employee not found");repo.deleteById(id);}
}
